version: "3"

services:
  database:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=yapp
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=pass

volumes:
  db-data:
